import os
from PIL import Image

# Mapping from index (0-98) to Brand Name (for A-Z sorting)
# Let's inspect and assign accurate names for all 99 client cards

names = {
    # Part 1: Slide 1
    0: "Aarts Industries",
    1: "ABB",
    2: "Aditya Birla",
    3: "Adani",
    4: "Alembic",
    5: "Ajanta Pharma",
    6: "Anoopam Mission",
    7: "Apollo Hospitals",
    8: "Apothecon Pharmaceuticals",
    9: "Armein Pharmaceuticals",
    10: "ATE",
    11: "Arkel",
    12: "Anupam",
    13: "Aadicura Super Speciality Hospital",
    14: "Anant National University",
    15: "Agni Solar / Agni",
    16: "Atul",
    17: "Borosil Renewables",
    18: "Bhalakia University / Bhalakia",
    19: "Baroda Dairy",
    20: "CGSM",
    21: "Cipla",
    22: "CHARUSAT",
    23: "DLFA",
    24: "Echjay Industries",
    25: "Elecon",
    26: "Elmex",
    27: "Epoxy House",
    28: "ERDA",
    29: "FMC",
    30: "Flint Group",
    31: "GACL (Gujarat Alkalies and Chemicals)",
    32: "Gala",
    33: "GCPL (Gujarat Chemical Port / Godrej)",
    34: "Gandhi Special Tubes",
    35: "GGRC (Gujarat Green Revolution Company)",
    36: "Encube Ethicals",
    37: "JSW Steel",
    38: "KSP",
    39: "KP Group",
    40: "KPGU Vadodara",
    41: "INEOS",
    42: "INOX-GSP / INOX",
    43: "Indian Oil (IOCL)",
    44: "MetTube",
    45: "Meghmani Group",
    46: "National Foods",
    47: "NJ Group",
    48: "Larsen & Toubro (L&T)",
    49: "OPAL (ONGC Petro additions)",
    50: "ORBIT / Oerlikon",
    51: "Pakona Engineers",
    52: "Toyo Engineering",
    53: "Sardar Sarovar Narmada Nigam (SSNNL)",
    
    # Part 2: Slide 2
    54: "Amneal Pharmaceuticals",
    55: "Banco",
    56: "Deepak Nitrite / Phenolics",
    57: "Gujarat Metal Cast",
    58: "GETCO",
    59: "GNFC",
    60: "GSRTC",
    61: "GSP Crop Science",
    62: "MGVCL",
    63: "Paramount Enterprises (PE)",
    64: "Pragati Glass",
    65: "Polycab",
    66: "Reliance Industries",
    67: "Shannen International School",
    68: "Shaily Engineering Plastics",
    69: "Silox",
    70: "Sudeep Pharma",
    71: "Shiva Pharmachem",
    72: "Signify",
    73: "Sintex",
    74: "Sisecam",
    75: "Unaty",
    76: "United Phosphorus (UPL)",
    77: "Sun Pharma",
    78: "Tara Suns",
    79: "Torrent Power",
    80: "TTK Prestige",
    81: "Pratibha Elecinfra",
    82: "Vedanta",
    83: "NDDB Dairy Services",
    84: "Central Warehousing Corporation",
    85: "UPL (United Phosphorus Limited)",
    86: "Utopia",
    87: "VCCI",
    88: "Welcare Hospital",
    89: "Welspun",
    90: "Indian Air Force (IAF)",
    91: "Western Railway",
    92: "Vadodara City Police",
    93: "Central Industrial Security Force (CISF)",
    94: "Vadodara Municipal Corporation (VMC)",
    95: "Government of India / Gujarat",
    96: "Gujarat Police",
    97: "Railway Protection Force / Police",
    98: "Zydus Cadila"
}

print(f"Total mapped: {len(names)} names.")
